name: powersync_endpoint
description: A Jepsen endpoint backend by PowerSync, and a local CLI fuzzer for PowerSync.
version: 0.0.1
repository: https://github.com/nurturenature/jepsen-powersync

environment:
  sdk: ^3.10.0

dependencies:
  args: ^2.7.0
  http: ^1.6.0
  jose: ^0.3.5
  list_utilities: ^1.0.3
  logging: ^1.2.0
  postgres: ^3.5.9
  powersync: ^1.16.1
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  synchronized: ^3.4.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
